apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: test-ai-chat
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: test-ai-chat
    apps.tanzu.vmware.com/carvel-package-workflow: "true"    
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
    - name: AI_API_KEY
      valueFrom:
        secretKeyRef:
          name: ai-api
          key: api-key
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1.5"           
  source:
    git:
      url: https://github.com/trisberg/test-ai-chat
      ref:
        branch: main

